### ISSUE TITLE
compile on windows - instructions?

### ISSUE THREAD

**Issue by dmitry-saritasa** [javanna/elasticshell#39]
Hi,

bin/elasticshell.bat
gives me:
Error: Unable to access jarfile lib/${project.build.finalName}.jar

**Comment by saritasa** [comment]
found it - http://dl.bintray.com/content/javanna/elasticsearch-tools/release/org/elasticsearch/elasticshell/0.90.0.RC2/elasticshell-0.90.0.RC2.zip?direct
